name: practice site
favicon: null
layout_spectrum: 0.4375841866713017
typography_spectrum: 0.5190824009478092
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.015344784129410982
  lightness: 0.6343568526208401
  saturation: 0.40030641853809357
  rhythmicContrast: 0.25
purpose: []
